service: aws-nodejs # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10

# you can overwrite defaults here
#  stage: dev
#  region: us-east-
  

  iamRoleStatements:
  - Effect: "Allow"
    Action:
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:BatchGetItem
      - dynamodb:GetRecords
    #Resource: "arn:aws:dynamodb:*:table/moodDb"   
    Resources:
      - 'Fn::Join':
        - ':'
        -
          - 'arn:aws:dynamodb'
          - Ref: 'AWS::Region'
          - Ref: 'AWS::AccountId'
          - 'table:/moodDb'


functions:
  hello:
    handler: handler.main

#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
    events:
      - http:
          path: /
          method: get
          cors: true

